<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action( 'genesis_post_title','genesis_do_post_title' );

//add_action( 'genesis_before_loop', 'genesis_do_search_title' );
add_action( 'genesis_after_header', 'uvasombims_do_search_title' );
/**
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function uvasombims_do_search_title() {

	$title = sprintf( '<div class="clearfix"></div><div id="uvasom_page_title">'.genesis_do_breadcrumbs().'<h1 class="archive-title">%s %s</h1>', apply_filters( 'genesis_search_title_text', __( 'Search Results for:', 'genesis' ) ), get_search_query() ).'</div>';

	echo apply_filters( 'genesis_search_title_output', $title ) . "\n";
}

genesis();
